Blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from myblog.models import Categories
from django_email_verification import urls as mail_urls

from Account.views import (
    login_view,
    registration_view,
    logout_view,
    dashboard,
)
from myblog.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('register/', registration_view, name="register"),
    path('login/', login_view, name="login"),
    path('email/', include(mail_urls)),
    path('dashboard/', dashboard, name="dashboard"),
    path('logout/', logout_view, name="logout"),
    path('create_blog/', create_blog, name="create_blog"),
    path('category/<str:cats>', category_view, name="category"),
    path('category/<str:pk>/details', blog_view, name="blog_view"),
    path('<str:room>/', chat, name="room"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

myblog/models.py
from Account.models import Account
from django.db import models
from django.conf import settings
from ckeditor.fields import RichTextField

class Categories(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title

# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False)
    categories = models.ManyToManyField(Categories)
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(upload_to = '')
    date_pub = models.DateTimeField(auto_now_add=True, verbose_name='Date Published')
    date_up = models.DateTimeField(auto_now=True, verbose_name='Date Updated')
    # author establishes rel between user(author) and blog post
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes = models.ManyToManyField(Account, related_name='blog_post')

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=255)
    body = models.TextField()

    def __str__(self):
        return '%s - %s' % (self.author, self.post)

'''class BestComment(models.Model):
    blog = models.OneToOneField(BlogPost, on_delete=models.PROTECT)
    comment = models.ForeignKey(Comment, on_delete=models.PROTECT)'''

templates/Blog_view.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}

  <title>Latest Blogs</title>

</head>
  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4"><text style="color:rgba(2, 0, 1, 0.651);">{{ blog.title }}</text>
        </h1>

        <!-- Blog Post -->
        <div class="card mb-4" id="all_blogs">
            <img class="card-img-top" src="{{ blog.image.url }}" alt="Card image cap">
          <div class="card-body" id="blog_body">
            Categories:
            {% for cat in blog.categories.all %}
            <text style="color:rgba(70, 6, 70, 0.603);">{{ cat.title }}</text>
            {% endfor %}
            <br>
            <u><text style="color:rgb(46, 10, 10); font-size: 30px; margin-left: 40%;">Overview</text></u>
            <br>
            {{ blog.body|safe }}
          </div>
          <div class="card-footer text-muted">
            Posted on {{ blog.date_pub|date }} by
            <a href="#">{{ blog.author }}</a>
            <br>
            <hr>
              <button type="submit", name="post_id", value="{{ blog.id }}" onclick="like()" id="like">
                like
              </button>
              Total Likes: {{ blog.likes.count }}
          </div>
          <h2>Comments..</h2>
          {% if not blog.comments.all %}
           No comments
          {% else %}
           {% for comment in blog.comments.all %}
            <b> {{ comment.author }} : {{ comment.body }}</b>
            {% endfor %}
          {% endif %}
          <input type="text" id="comment"><button type="submit" onclick="comment()">post comment</button>
        </div>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Navigate to Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  {% csrf_token %}
                  <a href="{% url 'home' %}" id="all">All</a>
                  {% for category in categories %}
                  <li>
                    <a href="{% url 'category' category.id %}" id="{{ category.id }}">{{ category }}</a>
                    <script>
                      {% include 'js/filter_category.js' %}
                    </script>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
  <script>
    {% include 'ajax_setup.js' %}
    function comment(){
      console.log($("#comment").val())
    $.ajax({
      type: "POST",
      data: {
        'comment': 1,
        'comment': $("#comment").val()
      },
      success: function(result){
        console.log(result);
        //$("#div1").html(result);
      }});
      }

      function like(){
    $.ajax({
      type: "POST",
      data: {
        'like': 1,
        'blog': $("#like").val()
      },
      success: function(result){
        console.log(result);
        //$("#div1").html(result);
      }});
      }
  </script>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'blog-home.css' %}">
    <title>Blog</title>
</head>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  
    {% if request.user.is_authenticated %}
    <a class="navbar-brand" href="#">Welcome, {{ user.first_name }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_blog' %}">Create_Blog</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      </ul>
    
    {% else %}
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
      </ul>
    </div>
    {% endif %}
  </div>
</nav>
<body>
    {% block content %}
    
    {% endblock content %}

</body>

</html>

templates/category.html
{% extends 'base.html' %}
{% block content %}
<style> {% include 'bootstrap/css/bootstrap.css' %} {% include 'bootstrap/css/blog-home.css' %} </style>
  {% load static %}
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">
<!-- Blog Post -->
<div class="card mb-4" id="all_blogs">
    {% for post in cats %}
    <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
    <div class="card-body">
      Categories:
      {% for cat in post.categories.all %}
       <text style="color:red;">{{ cat.title }}</text>
      {% endfor %}
        <h2 class="card-title">{{ post.title }}</h2>
      <a href="#" class="btn btn-primary">Read More &rarr;</a>
    </div>
    <div class="card-footer text-muted">
      Posted on {{ post.date_pub|date }} by
      <a href="#">{{ post.author }}</a>
    </div>
    {% endfor %}
  </div>
  </div>
  </div>
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
{% endblock content %}

templates/chat.html
Room name:{{room}}
<input id="input" type="text">
<button id="send" type="submit">send</button>
<div></div>
<textarea name="chatarea" id="chat" cols="30" rows="10"></textarea>
<script>
    const chatSocket = new WebSocket(
        'ws://' + 
        window.location.host +
        '/ws/'+
        '{{room}}' +
        '/'
    )

    chatSocket.onmessage = function (e)
    {
        const data = JSON.parse(e.data);
        console.log(data);
        document.querySelector('#chat').value += (data.tester+'\n');
    }

    document.querySelector('#send').onclick = function(e) {
        const message = document.querySelector('#input').value;
        if(message)
        {
            chatSocket.send(JSON.stringify({
                'message': message,
            }));
        }
        message.value = '';
    }
</script>

templates/confirm_template.html
{% include "login.html" %}
{% block content %}

{% if success %}

{{ user.first_name }}, your account is confirmed!
Click <a href="{% url 'login' %}">here</a> to login.

{% else %}
Error, invalid token!
{% endif %}
{% endblock content %}

templates/create_blog.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'create_blog.css' %}">
</head>
<body>
    <div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
		<h1 style="text-align: center;">Create Blog</h1>
        <br>
        {{ blog_form.media }}
		<div class="row">
			<h3 for="fname">Title of Blog</h3>
			<input type="text" name="title" id="title" placeholder="title" required autofocus>
        </div>
        <br>
        <div class="row">
				<h3 for="fname">Blog</h3>
            <div class="col-lg-12 nopadding">
                {{ blog_form.media }}
                {{ blog_form.body }}
            </div>
        </div>
        <br>
        <div class="row">
        <h3 for="image">Select image:</h3>
        {{ blog_form.image }}
        </div>
            <br>
            <div class="row">
                <h3 for="categories">Categories:</h3>
            <select style="max-width:20%;" name="categories" id="id_categories">
                {% for category in categories %}
                <option value="{{category.id}}" id="category">{{category}}</option>
                {% endfor %}
            </select>
        </div>
        {% for field in blog_form %}
        <p>
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        {% endfor %}
            {% if blog_form.non_field_errors %}
        <div style="color: red">
            <p>{{ blog_form.non_field_errors }}</p>
        </div>
            {% endif %}
            <button type="submit" class="btn btn-primary btn-lg">Post</button>
    </div>
    </form>

{% endblock content %}

templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}
<h5>Welcome, {{ user.first_name }}</h5>
<a class="p-2 text-dark" href="{% url 'logout' %}">Logout</a>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}

  <title>Latest Blogs</title>

</head>
  <!-- Page Content -->

  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4">Latest Blogs
        </h1>

        <!-- Blog Post -->
        <div class="card mb-4" id="all_blogs">
          {% for post in blog %}
          <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
          <div class="card-body">
            Categories:
            {% for cat in post.categories.all %}
             <text style="color:red;">{{ cat.title }}</text>
            {% endfor %}
              <h2 class="card-title">{{ post.title }}</h2>
              <a href="{% url 'blog_view' post.id %}" class="btn btn-primary">Read More &rarr;</a>
          </div>
          <div class="card-footer text-muted">
            Posted on {{ post.date_pub|date }} by
            <a href="#">{{ post.author }}</a>
          </div>
          {% endfor %}
        </div>

        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
          {% if blog.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?{{ page }}={{ blog.previous_page_number }}">&larr;</a>
          </li>
          {% endif %}
          <text class="page-link">{{ blog.number }}</text>
          {% if blog.has_next %}
          <li class="page-item">
            <a class="page-link" href="?{{ page }}={{ blog.next_page_number }}">&rarr;</a>
          </li>
          {% endif %}
        </ul>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" id="chat_room" class="form-control" placeholder="Search for...">
              <span class="input-group-append">
                <button id="my_btn" onclick="create_chat_room()" class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Navigate to Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  {% csrf_token %}
                  <a href="{% url 'home' %}" id="all">All</a>
                  {% for category in categories %}
                  <li>
                    <a href="{% url 'category' category.id %}" id="{{ category.id }}">{{ category }}</a>
                    <script>
                      {% include 'js/filter_category.js' %}
                    </script>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->
    <div id="result">

    </div>

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script>
    create_chat_room = () => 
    {
      var roomName = document.querySelector('#chat_room').value;
      if (roomName=='')
      {
        alert('Enter a chat room!');
      }
      else
      {
        window.location.pathname = '/' + roomName + '/';
      }
    }
  </script>
  {% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'login.css' %}">
  <link rel="stylesheet" href="{% static 'login.css.map' %}">
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <title>Login</title>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6 login-section-wrapper">
          <div class="brand-wrapper">
            <img src="{% static 'logo.svg' %}" alt="logo" class="logo">
          </div>
          <div class="login-wrapper my-auto">
            <h1 class="login-title">Log in</h1>
            <form method="POST">
              {% csrf_token %}
              <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" id="email" class="form-control" placeholder="email@example.com">
              </div>
              <div class="form-group mb-4">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" class="form-control" placeholder="enter your passsword">
              </div>
              <input name="login" id="login" class="btn btn-block login-btn" type="submit" value="Login">
            </form>
            <a href="#!" class="forgot-password-link">Forgot password?</a>
            <p class="login-wrapper-footer-text">Don't have an account? <a href="{% url 'register' %}" class="text-reset">Register here</a></p>
          </div>
        </div>
        <div class="col-sm-6 px-0 d-none d-sm-block">
          <img src="{% static 'login.jpg' %}" alt="login image" class="login-img">
        </div>
      </div>
    </div>
{% endblock content %}

templates/mail_body.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Confirmation</title>
</head>
<body>
<h1>You are almost there, {{ user.username }}!</h1><br>
<h2>Please click <a href="{{ link }}">here</a> to confirm your account</h2>
<h2>The token expires on {{ expiry|time:"TIME_FORMAT" }}</h2>
</body>
</html>

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
<title>Login</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
<link rel="stylesheet" href="{% static 'registration.css' %}">
</head>
<body>
<div class="signup-form">
	<span id='confirm_mail'></span>
    <form id="signup" method="POST">
		{% csrf_token %}
		<h2>Sign Up</h2>
		<p>Please fill in this form to create an account!</p>
		<hr>
        <div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-user"></span>
					</span>                    
				</div>
				<input type="text" name="first_name" id="inputFirstName" class="form-control" placeholder="Name" required autofocus>
			</div>
		</div>
		
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<span class="fa fa-user"></span>
					</span>                    
				</div>
				<input type="text" name="last_name" id="inputLastName" class="form-control" placeholder="Last Name" required autofocus>
			</div>
        </div>
        
        <div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<i class="fa fa-paper-plane"></i>
					</span>                    
				</div>
				<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
			</div>
        </div>
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<i class="fa fa-lock"></i>
					</span>                    
				</div>
				<input type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>

			</div>
        </div>
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<i class="fa fa-lock"></i>
						<i class="fa fa-check"></i>
					</span>                    
				</div>
                <input type="password" name="password2" id="inputPassword2" class="form-control" placeholder="Confirm Password" required>

			</div>
        </div>
        <div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<i class="fa fa-lock"></i>
						<i class="fa fa-check"></i>
					</span>                    
                </div>
                <input type="date" name="dob" id="inputDOB" class="form-control" placeholder="" required autofocus>

			</div>
        </div>
        <div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<i class="fa fa-lock"></i>
						<i class="fa fa-check"></i>
					</span>                    
                </div>
                <input type="text" name="city" id="inputCity" class="form-control" placeholder="City" required>


			</div>
        </div>
        <div class="form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<span class="input-group-text">
						<i class="fa fa-lock"></i>
						<i class="fa fa-check"></i>
					</span>                    
                </div>
                <input type="text" name="about" id="inputAbout" class="form-control" placeholder="About" required autofocus>

			</div>
        </div>
        <div class="form-group">
			<label class="form-check-label"><input type="checkbox" required="required"> I accept the <a href="#">Terms of Use</a> &amp; <a href="#">Privacy Policy</a></label>
        </div>
        {% for field in registration_form %}
        <p>
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        {% endfor %}
            {% if registration_form.non_field_errors %}
        <div style="color: red">
            <p>{{ registration_form.non_field_errors }}</p>
        </div>
            {% endif %}
		<div class="form-group">
            <input type="submit" class="btn btn-primary btn-lg"/>
        </div>
    </form>
	<div class="text-center">Already have an account? <a href="{% url 'login' %}">Login here</a></div>
</div>
<script>
	{% include 'ajax_setup.js' %}
	$("#signup").submit(function (e)
	{
		e.preventDefault();
		var serializedData = $(this).serialize();
		console.log(serializedData);
		$.ajax({
            method: 'POST',
            
            data:
                serializedData,
            success: function (data) {
				console.log(data);
                $("#confirm_mail").html(data['instance']);
            },
            error: function (error) {
                console.log(error);
            }
        });
		/*if ($("#signup")[0].checkValidity())
		{
			$("#confirm_mail").html('A mail has been sent to your email id. Please validate to activate your account');
		}*/
	});
</script>
{% endblock content %}